---
language: python
services:
  - docker
install:
  - pip install molecule docker
script:
  - tox
  - molecule --version
  - ansible --version
  - molecule lint
  - molecule syntax
  - molecule test
